### ISSUE TITLE
Cannot build functional ISO

### ISSUE THREAD

**Issue by LibreAria** [UnclePunch/Training-Mode#19]
I try to follow the instructions to the best of my ability, but I still, for the past several months, cannot seem to make a functional UnclePunch build.

I am able to get the start.dol and the codes.gct to be created as stated in the instructions. I also know how to rebuild the ISO in GCR. Unfortunately, I simply get ISOs that do not work.

Trial 1: I checked both Modify System Files and Do not use game.toc options so that I can use the additional files in Additional ISO Files. I replace the original start.dol in the system folder with the new one as created from the batch file. However, when I rebuild the ISO and run it in Slippi r18, I get the following errors:

IntCPU: Unknown instruction 00000000 at PC = 00000018 last_PC = 9001f18 LR = 8066f7c8
Invalid read from 0xffff9f3d, PC = 0x0000001c

Trial 2: I leave the original start.dol in the system folder and put the new start.dol with the other files in the root folder. Everything else is same as trial 1. This time, the game is simply vanilla melee.

I do not know what is happening, and I am lost in terms of how to approach this problem. I was hoping someone else would have had this problem and vocalized it, but this was enough for me to create an account to ask for help. I am open to suggestions. Thank you.

**Comment by angelichorsey** [comment]
AFAICT this is a propriety product requiring payment (donation) and as such it cannot be built from the public source.

If you find a way to build it, help out others and post it somewhere.

**Comment by LibreAria** [comment]
Understandable have a nice day
